### ISSUE TITLE
Error Zabbix trigger

### ISSUE THREAD

**Issue by xdexter** [alexanderzobnin/grafana-zabbix#470]
### I'm submitting a ...
- [ X ] Bug report
- [ ] Feature requestdd
- [ ] Question / Support request

### For bug report please include this information:

**Software Versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
|  v4.6.0-beta2 (commit: fff4cfd)  | 2.4.8  | 3.6.1  |

#### What did you do?
I'm trying add "Zabbix Triggers" panel;

#### What was the expected result?
Panel added with success;

#### What happened instead?
When i click in Add panel i have this error:

![zabbix_error1](https://user-images.githubusercontent.com/10849509/31890316-7157e42a-b7e1-11e7-9e62-9161aff0d778.png)

And in console of browser:

> Plugin component error Error: Fetch error: 404 Not Found
>   Instantiating http://grafana.domain.com.br/public/tether-drop
>   Loading http://grafana.domain.com.br/public/plugins/alexanderzobnin-zabbix-app/panel-triggers/ack-tooltip.directive.js
>   Loading plugins/alexanderzobnin-zabbix-app/panel-triggers/module
>     at index.js:33
>     at <anonymous>

Someone could help me please?

Regards

**Comment by alexanderzobnin** [comment]
Was fixed in 630dd176595f824535a1bc299245ff2b531d4a18 Wait for the new release or upgrade from master branch.

**Comment by xdexter** [comment]
Hi @alexanderzobnin ,

Right, and do you know when it's will occur? There are some aproximate date?

Regards

**Comment by alexanderzobnin** [comment]
Going to release next version this week.

**Comment by xdexter** [comment]
Hm ok, so i will wait this new version, thank you!

**Comment by aviramartac** [comment]
Hi, upgraded from master branch and the issue is still there. version 3.7.0.

**Comment by alexanderzobnin** [comment]
@aviramartac you should clean up browser cache.

**Comment by rodrigoredes** [comment]
Deu certo após a atulização.

**Comment by areytsman** [comment]
I confirm the need to clear the cache.
