### ISSUE TITLE
Zabbix Events Error - Cannot read property 'description' of undefined

### ISSUE THREAD

**Issue by cloudlgti** [alexanderzobnin/grafana-zabbix#954]
**Describe the bug**
When show many problem  in painel Zabbix Problem:

Error: Cannot read property 'description' of undefined
![Captura de Tela 2020-05-21 às 16 42 04](https://user-images.githubusercontent.com/50424091/82599053-02029980-9b82-11ea-8fd3-19fc07cfb78e.png)

**Software versions**
| Grafana | Zabbix | Grafana-Zabbix Plugin |
| 7.0          | 4. 4.5          |3.12.0 |

**Comment by duuz** [comment]
+1

**Comment by DanilaZaytsev** [comment]
+1

**Comment by JSylvia007** [comment]
+1

**Comment by Andorash** [comment]
+1

**Comment by alexanderzobnin** [comment]
Could someone show the query? Can't replicate it on my instance.

**Comment by duuz** [comment]
**JSON - PANEL DATA**
{
  "state": "Error",
  "series": [],
  "request": {
    "app": "dashboard",
    "requestId": "Q120",
    "timezone": "browser",
    "panelId": 23763571993,
    "dashboardId": 13,
    "range": {
      "from": "2020-05-15T08:49:31.709Z",
      "to": "2020-05-22T08:49:31.709Z",
      "raw": {
        "from": "now-7d",
        "to": "now"
      }
    },
    "timeInfo": "",
    "interval": "5m",
    "intervalMs": 300000,
    "targets": [
      {
        "application": {
          "filter": ""
        },
        "group": {
          "filter": "Zabbix servers"
        },
        "host": {
          "filter": "/.*/"
        },
        "proxy": {
          "filter": ""
        },
        "refId": "A",
        "tags": {
          "filter": ""
        },
        "trigger": {
          "filter": ""
        },
        "queryType": 5,
        "showProblems": "problems",
        "options": {
          "hostsInMaintenance": true,
          "sortProblems": "default",
          "minSeverity": 0,
          "acknowledged": 2,
          "limit": 1001,
          "showDisabledItems": false,
          "skipEmptyValues": false,
          "hostProxy": false
        },
        "resultFormat": "time_series",
        "item": {
          "filter": ""
        },
        "functions": [],
        "triggers": {
          "count": true,
          "minSeverity": 3,
          "acknowledged": 2
        },
        "table": {
          "skipEmptyValues": false
        },
        "datasource": "Zabbix Server"
      }
    ],
    "maxDataPoints": 1870,
    "scopedVars": {
      "__interval": {
        "text": "5m",
        "value": "5m"
      },
      "__interval_ms": {
        "text": "300000",
        "value": 300000
      },
      "__range_ms": {
        "text": 604800000,
        "value": 604800000
      },
      "__range_s": {
        "text": 604800,
        "value": 604800
      },
      "__range": {
        "text": "7d",
        "value": "7d"
      },
      "__range_series": {
        "text": "range_series",
        "value": "range_series"
      }
    },
    "startTime": 1590137371710,
    "rangeRaw": {
      "from": "now-7d",
      "to": "now"
    }
  },
  "timeRange": {
    "from": "2020-05-15T08:49:31.709Z",
    "to": "2020-05-22T08:49:31.709Z",
    "raw": {
      "from": "now-7d",
      "to": "now"
    }
  },
  "error": {},
  "timings": {
    "dataProcessingTime": 0.0700000086799264
  }
}

**Error**

Cannot read property 'description' of undefined

**Query**

Refresh loads but nothing happens



Software versions
| Grafana | Zabbix | Grafana-Zabbix Plugin |
| 7.0 | 4. 4.7 |3.12.0 |

**Comment by alexanderzobnin** [comment]
@duuz Could you post a response from the query inspector?

**Comment by duuz** [comment]
@alexanderzobnin 


{
  "request": {
    "method": "POST",
    "url": "api/datasources/proxy/5",
    "data": {
      "jsonrpc": "2.0",
      "method": "trend.get",
      "params": {
        "output": "extend",
        "trend": "0",
        "itemids": [
          "2612714",
          "2612715"
        ],
        "sortfield": "clock",
        "sortorder": "ASC",
        "time_from": 1589535595,
        "time_till": 1590140395
      },
      "id": 1,
      "auth": "0fc78d87361f4f4ec453cc8a8c79e8fe"
    }
  },
  "response": {
    "jsonrpc": "2.0",
    "result": [
      {
        "itemid": "2612714",
        "clock": "1589540400",
        "num": "1",
        "value_min": "46.2782",
        "value_avg": "46.2782",
        "value_max": "46.2782"
      },
      {
        "itemid": "2612714",
        "clock": "1589547600",
        "num": "1",
        "value_min": "46.3532",
        "value_avg": "46.3532",
        "value_max": "46.3532"
      },
      {
        "itemid": "2612714",
        "clock": "1589554800",
        "num": "1",
        "value_min": "46.4583",
        "value_avg": "46.4583",
        "value_max": "46.4583"
      },
      {
        "itemid": "2612714",
        "clock": "1589562000",
        "num": "1",
        "value_min": "46.5468",
        "value_avg": "46.5468",
        "value_max": "46.5468"
      },
      {
        "itemid": "2612714",
        "clock": "1589569200",
        "num": "1",
        "value_min": "45.8197",
        "value_avg": "45.8197",
        "value_max": "45.8197"
      },
      {
        "itemid": "2612714",
        "clock": "1589576400",
        "num": "1",
        "value_min": "45.9019",
        "value_avg": "45.9019",
        "value_max": "45.9019"
      },
      {
        "itemid": "2612714",
        "clock": "1589583600",
        "num": "1",
        "value_min": "45.9608",
        "value_avg": "45.9608",
        "value_max": "45.9608"
      },
      {
        "itemid": "2612714",
        "clock": "1589590800",
        "num": "1",
        "value_min": "46.0318",
        "value_avg": "46.0318",
        "value_max": "46.0318"
      },
      {
        "itemid": "2612714",
        "clock": "1589598000",
        "num": "1",
        "value_min": "46.1422",
        "value_avg": "46.1422",
        "value_max": "46.1422"
      },
      {
        "itemid": "2612714",
        "clock": "1589605200",
        "num": "1",
        "value_min": "46.1645",
        "value_avg": "46.1645",
        "value_max": "46.1645"
      },
      {
        "itemid": "2612714",
        "clock": "1589612400",
        "num": "1",
        "value_min": "46.2522",
        "value_avg": "46.2522",
        "value_max": "46.2522"
      },
      {
        "itemid": "2612714",
        "clock": "1589619600",
        "num": "1",
        "value_min": "46.3228",
        "value_avg": "46.3228",
        "value_max": "46.3228"
      },
      {
        "itemid": "2612714",
        "clock": "1589626800",
        "num": "1",
        "value_min": "46.4041",
        "value_avg": "46.4041",
        "value_max": "46.4041"
      },
      {
        "itemid": "2612714",
        "clock": "1589634000",
        "num": "1",
        "value_min": "46.4722",
        "value_avg": "46.4722",
        "value_max": "46.4722"
      },
      {
        "itemid": "2612714",
        "clock": "1589641200",
        "num": "1",
        "value_min": "46.5748",
        "value_avg": "46.5748",
        "value_max": "46.5748"
      },
      {
        "itemid": "2612714",
        "clock": "1589648400",
        "num": "1",
        "value_min": "46.6617",
        "value_avg": "46.6617",
        "value_max": "46.6617"
      },
      {
        "itemid": "2612714",
        "clock": "1589655600",
        "num": "1",
        "value_min": "45.9411",
        "value_avg": "45.9411",
        "value_max": "45.9411"
      },
      {
        "itemid": "2612714",
        "clock": "1589662800",
        "num": "1",
        "value_min": "46.0207",
        "value_avg": "46.0207",
        "value_max": "46.0207"
      },
      {
        "itemid": "2612714",
        "clock": "1589670000",
        "num": "1",
        "value_min": "46.0845",
        "value_avg": "46.0845",
        "value_max": "46.0845"
      },
      {
        "itemid": "2612714",
        "clock": "1589677200",
        "num": "1",
        "value_min": "46.1550",
        "value_avg": "46.1550",
        "value_max": "46.1550"
      },
      {
        "itemid": "2612714",
        "clock": "1589684400",
        "num": "1",
        "value_min": "46.2665",
        "value_avg": "46.2665",
        "value_max": "46.2665"
      },
      {
        "itemid": "2612714",
        "clock": "1589691600",
        "num": "1",
        "value_min": "46.2902",
        "value_avg": "46.2902",
        "value_max": "46.2902"
      },
      {
        "itemid": "2612714",
        "clock": "1589698800",
        "num": "1",
        "value_min": "46.3579",
        "value_avg": "46.3579",
        "value_max": "46.3579"
      },
      {
        "itemid": "2612714",
        "clock": "1589706000",
        "num": "1",
        "value_min": "46.4736",
        "value_avg": "46.4736",
        "value_max": "46.4736"
      },
      {
        "itemid": "2612714",
        "clock": "1589713200",
        "num": "1",
        "value_min": "46.5164",
        "value_avg": "46.5164",
        "value_max": "46.5164"
      },
      {
        "itemid": "2612714",
        "clock": "1589720400",
        "num": "1",
        "value_min": "46.6004",
        "value_avg": "46.6004",
        "value_max": "46.6004"
      },
      {
        "itemid": "2612714",
        "clock": "1589727600",
        "num": "1",
        "value_min": "46.7055",
        "value_avg": "46.7055",
        "value_max": "46.7055"
      },
      {
        "itemid": "2612714",
        "clock": "1589734800",
        "num": "1",
        "value_min": "46.7761",
        "value_avg": "46.7761",
        "value_max": "46.7761"
      },
      {
        "itemid": "2612714",
        "clock": "1589742000",
        "num": "1",
        "value_min": "46.0558",
        "value_avg": "46.0558",
        "value_max": "46.0558"
      },
      {
        "itemid": "2612714",
        "clock": "1589749200",
        "num": "1",
        "value_min": "46.1481",
        "value_avg": "46.1481",
        "value_max": "46.1481"
      },
      {
        "itemid": "2612714",
        "clock": "1589756400",
        "num": "1",
        "value_min": "46.2252",
        "value_avg": "46.2252",
        "value_max": "46.2252"
      },
      {
        "itemid": "2612714",
        "clock": "1589763600",
        "num": "1",
        "value_min": "46.2933",
        "value_avg": "46.2933",
        "value_max": "46.2933"
      },
      {
        "itemid": "2612714",
        "clock": "1589770800",
        "num": "1",
        "value_min": "46.3877",
        "value_avg": "46.3877",
        "value_max": "46.3877"
      },
      {
        "itemid": "2612714",
        "clock": "1589778000",
        "num": "1",
        "value_min": "46.4159",
        "value_avg": "46.4159",
        "value_max": "46.4159"
      },
      {
        "itemid": "2612714",
        "clock": "1589785200",
        "num": "1",
        "value_min": "46.4769",
        "value_avg": "46.4769",
        "value_max": "46.4769"
      },
      {
        "itemid": "2612714",
        "clock": "1589792400",
        "num": "1",
        "value_min": "46.5742",
        "value_avg": "46.5742",
        "value_max": "46.5742"
      },
      {
        "itemid": "2612714",
        "clock": "1589799600",
        "num": "1",
        "value_min": "46.6590",
        "value_avg": "46.6590",
        "value_max": "46.6590"
      },
      {
        "itemid": "2612714",
        "clock": "1589806800",
        "num": "1",
        "value_min": "46.7259",
        "value_avg": "46.7259",
        "value_max": "46.7259"
      },
      {
        "itemid": "2612714",
        "clock": "1589814000",
        "num": "1",
        "value_min": "46.8166",
        "value_avg": "46.8166",
        "value_max": "46.8166"
      },
      {
        "itemid": "2612714",
        "clock": "1589821200",
        "num": "1",
        "value_min": "46.8924",
        "value_avg": "46.8924",
        "value_max": "46.8924"
      },
      {
        "itemid": "2612714",
        "clock": "1589828400",
        "num": "1",
        "value_min": "46.1814",
        "value_avg": "46.1814",
        "value_max": "46.1814"
      },
      {
        "itemid": "2612714",
        "clock": "1589835600",
        "num": "1",
        "value_min": "46.2796",
        "value_avg": "46.2796",
        "value_max": "46.2796"
      },
      {
        "itemid": "2612714",
        "clock": "1589842800",
        "num": "1",
        "value_min": "46.3657",
        "value_avg": "46.3657",
        "value_max": "46.3657"
      },
      {
        "itemid": "2612714",
        "clock": "1589850000",
        "num": "1",
        "value_min": "46.4537",
        "value_avg": "46.4537",
        "value_max": "46.4537"
      },
      {
        "itemid": "2612714",
        "clock": "1589857200",
        "num": "1",
        "value_min": "46.5484",
        "value_avg": "46.5484",
        "value_max": "46.5484"
      },
      {
        "itemid": "2612714",
        "clock": "1589864400",
        "num": "1",
        "value_min": "46.5608",
        "value_avg": "46.5608",
        "value_max": "46.5608"
      },
      {
        "itemid": "2612714",
        "clock": "1589871600",
        "num": "1",
        "value_min": "46.6272",
        "value_avg": "46.6272",
        "value_max": "46.6272"
      },
      {
        "itemid": "2612714",
        "clock": "1589878800",
        "num": "1",
        "value_min": "46.7252",
        "value_avg": "46.7252",
        "value_max": "46.7252"
      },
      {
        "itemid": "2612714",
        "clock": "1589886000",
        "num": "1",
        "value_min": "46.8117",
        "value_avg": "46.8117",
        "value_max": "46.8117"
      },
      {
        "itemid": "2612714",
        "clock": "1589893200",
        "num": "1",
        "value_min": "46.8895",
        "value_avg": "46.8895",
        "value_max": "46.8895"
      },
      {
        "itemid": "2612714",
        "clock": "1589900400",
        "num": "1",
        "value_min": "46.9873",
        "value_avg": "46.9873",
        "value_max": "46.9873"
      },
      {
        "itemid": "2612714",
        "clock": "1589907600",
        "num": "1",
        "value_min": "47.0665",
        "value_avg": "47.0665",
        "value_max": "47.0665"
      },
      {
        "itemid": "2612714",
        "clock": "1589914800",
        "num": "1",
        "value_min": "46.4388",
        "value_avg": "46.4388",
        "value_max": "46.4388"
      },
      {
        "itemid": "2612714",
        "clock": "1589922000",
        "num": "1",
        "value_min": "46.5629",
        "value_avg": "46.5629",
        "value_max": "46.5629"
      },
      {
        "itemid": "2612714",
        "clock": "1589929200",
        "num": "1",
        "value_min": "46.6243",
        "value_avg": "46.6243",
        "value_max": "46.6243"
      },
      {
        "itemid": "2612714",
        "clock": "1589936400",
        "num": "1",
        "value_min": "46.6950",
        "value_avg": "46.6950",
        "value_max": "46.6950"
      },
      {
        "itemid": "2612714",
        "clock": "1589943600",
        "num": "1",
        "value_min": "46.7787",
        "value_avg": "46.7787",
        "value_max": "46.7787"
      },
      {
        "itemid": "2612714",
        "clock": "1589950800",
        "num": "1",
        "value_min": "46.8184",
        "value_avg": "46.8184",
        "value_max": "46.8184"
      },
      {
        "itemid": "2612714",
        "clock": "1589958000",
        "num": "1",
        "value_min": "46.8863",
        "value_avg": "46.8863",
        "value_max": "46.8863"
      },
      {
        "itemid": "2612714",
        "clock": "1589965200",
        "num": "1",
        "value_min": "46.9696",
        "value_avg": "46.9696",
        "value_max": "46.9696"
      },
      {
        "itemid": "2612714",
        "clock": "1589972400",
        "num": "1",
        "value_min": "47.0417",
        "value_avg": "47.0417",
        "value_max": "47.0417"
      },
      {
        "itemid": "2612714",
        "clock": "1589979600",
        "num": "1",
        "value_min": "47.1297",
        "value_avg": "47.1297",
        "value_max": "47.1297"
      },
      {
        "itemid": "2612714",
        "clock": "1589986800",
        "num": "1",
        "value_min": "47.2249",
        "value_avg": "47.2249",
        "value_max": "47.2249"
      },
      {
        "itemid": "2612714",
        "clock": "1589994000",
        "num": "1",
        "value_min": "47.2999",
        "value_avg": "47.2999",
        "value_max": "47.2999"
      },
      {
        "itemid": "2612714",
        "clock": "1590001200",
        "num": "1",
        "value_min": "46.5646",
        "value_avg": "46.5646",
        "value_max": "46.5646"
      },
      {
        "itemid": "2612714",
        "clock": "1590008400",
        "num": "1",
        "value_min": "46.6640",
        "value_avg": "46.6640",
        "value_max": "46.6640"
      },
      {
        "itemid": "2612714",
        "clock": "1590015600",
        "num": "1",
        "value_min": "46.7159",
        "value_avg": "46.7159",
        "value_max": "46.7159"
      },
      {
        "itemid": "2612714",
        "clock": "1590022800",
        "num": "1",
        "value_min": "46.7950",
        "value_avg": "46.7950",
        "value_max": "46.7950"
      },
      {
        "itemid": "2612714",
        "clock": "1590030000",
        "num": "1",
        "value_min": "46.9037",
        "value_avg": "46.9037",
        "value_max": "46.9037"
      },
      {
        "itemid": "2612714",
        "clock": "1590037200",
        "num": "1",
        "value_min": "46.9266",
        "value_avg": "46.9266",
        "value_max": "46.9266"
      },
      {
        "itemid": "2612714",
        "clock": "1590048000",
        "num": "1",
        "value_min": "46.9347",
        "value_avg": "46.9347",
        "value_max": "46.9347"
      },
      {
        "itemid": "2612714",
        "clock": "1590058800",
        "num": "1",
        "value_min": "46.9449",
        "value_avg": "46.9449",
        "value_max": "46.9449"
      },
      {
        "itemid": "2612714",
        "clock": "1590066000",
        "num": "1",
        "value_min": "47.2005",
        "value_avg": "47.2005",
        "value_max": "47.2005"
      },
      {
        "itemid": "2612714",
        "clock": "1590073200",
        "num": "1",
        "value_min": "47.2261",
        "value_avg": "47.2261",
        "value_max": "47.2261"
      },
      {
        "itemid": "2612714",
        "clock": "1590080400",
        "num": "1",
        "value_min": "47.3178",
        "value_avg": "47.3178",
        "value_max": "47.3178"
      },
      {
        "itemid": "2612714",
        "clock": "1590087600",
        "num": "1",
        "value_min": "46.5904",
        "value_avg": "46.5904",
        "value_max": "46.5904"
      },
      {
        "itemid": "2612714",
        "clock": "1590102000",
        "num": "1",
        "value_min": "46.7454",
        "value_avg": "46.7454",
        "value_max": "46.7454"
      },
      {
        "itemid": "2612714",
        "clock": "1590109200",
        "num": "1",
        "value_min": "46.8198",
        "value_avg": "46.8198",
        "value_max": "46.8198"
      },
      {
        "itemid": "2612714",
        "clock": "1590116400",
        "num": "1",
        "value_min": "46.8835",
        "value_avg": "46.8835",
        "value_max": "46.8835"
      },
      {
        "itemid": "2612714",
        "clock": "1590123600",
        "num": "1",
        "value_min": "46.9076",
        "value_avg": "46.9076",
        "value_max": "46.9076"
      },
      {
        "itemid": "2612714",
        "clock": "1590130800",
        "num": "1",
        "value_min": "47.0126",
        "value_avg": "47.0126",
        "value_max": "47.0126"
      },
      {
        "itemid": "2612715",
        "clock": "1589540400",
        "num": "1",
        "value_min": "15.1482",
        "value_avg": "15.1482",
        "value_max": "15.1482"
      },
      {
        "itemid": "2612715",
        "clock": "1589547600",
        "num": "1",
        "value_min": "15.1672",
        "value_avg": "15.1672",
        "value_max": "15.1672"
      },
      {
        "itemid": "2612715",
        "clock": "1589554800",
        "num": "1",
        "value_min": "15.1922",
        "value_avg": "15.1922",
        "value_max": "15.1922"
      },
      {
        "itemid": "2612715",
        "clock": "1589562000",
        "num": "1",
        "value_min": "15.2059",
        "value_avg": "15.2059",
        "value_max": "15.2059"
      },
      {
        "itemid": "2612715",
        "clock": "1589569200",
        "num": "1",
        "value_min": "15.2245",
        "value_avg": "15.2245",
        "value_max": "15.2245"
      },
      {
        "itemid": "2612715",
        "clock": "1589576400",
        "num": "1",
        "value_min": "15.2363",
        "value_avg": "15.2363",
        "value_max": "15.2363"
      },
      {
        "itemid": "2612715",
        "clock": "1589583600",
        "num": "1",
        "value_min": "15.2495",
        "value_avg": "15.2495",
        "value_max": "15.2495"
      },
      {
        "itemid": "2612715",
        "clock": "1589590800",
        "num": "1",
        "value_min": "15.2714",
        "value_avg": "15.2714",
        "value_max": "15.2714"
      },
      {
        "itemid": "2612715",
        "clock": "1589598000",
        "num": "1",
        "value_min": "15.0274",
        "value_avg": "15.0274",
        "value_max": "15.0274"
      },
      {
        "itemid": "2612715",
        "clock": "1589605200",
        "num": "1",
        "value_min": "15.0635",
        "value_avg": "15.0635",
        "value_max": "15.0635"
      },
      {
        "itemid": "2612715",
        "clock": "1589612400",
        "num": "1",
        "value_min": "15.0975",
        "value_avg": "15.0975",
        "value_max": "15.0975"
      },
      {
        "itemid": "2612715",
        "clock": "1589619600",
        "num": "1",
        "value_min": "15.1273",
        "value_avg": "15.1273",
        "value_max": "15.1273"
      },
      {
        "itemid": "2612715",
        "clock": "1589626800",
        "num": "1",
        "value_min": "15.1519",
        "value_avg": "15.1519",
        "value_max": "15.1519"
      },
      {
        "itemid": "2612715",
        "clock": "1589634000",
        "num": "1",
        "value_min": "15.1698",
        "value_avg": "15.1698",
        "value_max": "15.1698"
      },
      {
        "itemid": "2612715",
        "clock": "1589641200",
        "num": "1",
        "value_min": "15.1928",
        "value_avg": "15.1928",
        "value_max": "15.1928"
      },
      {
        "itemid": "2612715",
        "clock": "1589648400",
        "num": "1",
        "value_min": "15.2135",
        "value_avg": "15.2135",
        "value_max": "15.2135"
      },
      {
        "itemid": "2612715",
        "clock": "1589655600",
        "num": "1",
        "value_min": "15.2291",
        "value_avg": "15.2291",
        "value_max": "15.2291"
      },
      {
        "itemid": "2612715",
        "clock": "1589662800",
        "num": "1",
        "value_min": "15.2402",
        "value_avg": "15.2402",
        "value_max": "15.2402"
      },
      {
        "itemid": "2612715",
        "clock": "1589670000",
        "num": "1",
        "value_min": "15.2515",
        "value_avg": "15.2515",
        "value_max": "15.2515"
      },
      {
        "itemid": "2612715",
        "clock": "1589677200",
        "num": "1",
        "value_min": "15.2611",
        "value_avg": "15.2611",
        "value_max": "15.2611"
      },
      {
        "itemid": "2612715",
        "clock": "1589684400",
        "num": "1",
        "value_min": "15.0244",
        "value_avg": "15.0244",
        "value_max": "15.0244"
      },
      {
        "itemid": "2612715",
        "clock": "1589691600",
        "num": "1",
        "value_min": "15.0671",
        "value_avg": "15.0671",
        "value_max": "15.0671"
      },
      {
        "itemid": "2612715",
        "clock": "1589698800",
        "num": "1",
        "value_min": "15.0997",
        "value_avg": "15.0997",
        "value_max": "15.0997"
      },
      {
        "itemid": "2612715",
        "clock": "1589706000",
        "num": "1",
        "value_min": "15.1264",
        "value_avg": "15.1264",
        "value_max": "15.1264"
      },
      {
        "itemid": "2612715",
        "clock": "1589713200",
        "num": "1",
        "value_min": "15.1525",
        "value_avg": "15.1525",
        "value_max": "15.1525"
      },
      {
        "itemid": "2612715",
        "clock": "1589720400",
        "num": "1",
        "value_min": "15.1707",
        "value_avg": "15.1707",
        "value_max": "15.1707"
      },
      {
        "itemid": "2612715",
        "clock": "1589727600",
        "num": "1",
        "value_min": "15.1910",
        "value_avg": "15.1910",
        "value_max": "15.1910"
      },
      {
        "itemid": "2612715",
        "clock": "1589734800",
        "num": "1",
        "value_min": "15.2057",
        "value_avg": "15.2057",
        "value_max": "15.2057"
      },
      {
        "itemid": "2612715",
        "clock": "1589742000",
        "num": "1",
        "value_min": "15.2290",
        "value_avg": "15.2290",
        "value_max": "15.2290"
      },
      {
        "itemid": "2612715",
        "clock": "1589749200",
        "num": "1",
        "value_min": "15.2454",
        "value_avg": "15.2454",
        "value_max": "15.2454"
      },
      {
        "itemid": "2612715",
        "clock": "1589756400",
        "num": "1",
        "value_min": "15.2594",
        "value_avg": "15.2594",
        "value_max": "15.2594"
      },
      {
        "itemid": "2612715",
        "clock": "1589763600",
        "num": "1",
        "value_min": "15.2677",
        "value_avg": "15.2677",
        "value_max": "15.2677"
      },
      {
        "itemid": "2612715",
        "clock": "1589770800",
        "num": "1",
        "value_min": "15.0284",
        "value_avg": "15.0284",
        "value_max": "15.0284"
      },
      {
        "itemid": "2612715",
        "clock": "1589778000",
        "num": "1",
        "value_min": "15.0627",
        "value_avg": "15.0627",
        "value_max": "15.0627"
      },
      {
        "itemid": "2612715",
        "clock": "1589785200",
        "num": "1",
        "value_min": "15.0943",
        "value_avg": "15.0943",
        "value_max": "15.0943"
      },
      {
        "itemid": "2612715",
        "clock": "1589792400",
        "num": "1",
        "value_min": "15.1307",
        "value_avg": "15.1307",
        "value_max": "15.1307"
      },
      {
        "itemid": "2612715",
        "clock": "1589799600",
        "num": "1",
        "value_min": "15.1552",
        "value_avg": "15.1552",
        "value_max": "15.1552"
      },
      {
        "itemid": "2612715",
        "clock": "1589806800",
        "num": "1",
        "value_min": "15.1724",
        "value_avg": "15.1724",
        "value_max": "15.1724"
      },
      {
        "itemid": "2612715",
        "clock": "1589814000",
        "num": "1",
        "value_min": "15.1928",
        "value_avg": "15.1928",
        "value_max": "15.1928"
      },
      {
        "itemid": "2612715",
        "clock": "1589821200",
        "num": "1",
        "value_min": "15.2102",
        "value_avg": "15.2102",
        "value_max": "15.2102"
      },
      {
        "itemid": "2612715",
        "clock": "1589828400",
        "num": "1",
        "value_min": "15.2218",
        "value_avg": "15.2218",
        "value_max": "15.2218"
      },
      {
        "itemid": "2612715",
        "clock": "1589835600",
        "num": "1",
        "value_min": "15.2538",
        "value_avg": "15.2538",
        "value_max": "15.2538"
      },
      {
        "itemid": "2612715",
        "clock": "1589842800",
        "num": "1",
        "value_min": "15.2666",
        "value_avg": "15.2666",
        "value_max": "15.2666"
      },
      {
        "itemid": "2612715",
        "clock": "1589850000",
        "num": "1",
        "value_min": "15.2742",
        "value_avg": "15.2742",
        "value_max": "15.2742"
      },
      {
        "itemid": "2612715",
        "clock": "1589857200",
        "num": "1",
        "value_min": "15.0276",
        "value_avg": "15.0276",
        "value_max": "15.0276"
      },
      {
        "itemid": "2612715",
        "clock": "1589864400",
        "num": "1",
        "value_min": "15.0622",
        "value_avg": "15.0622",
        "value_max": "15.0622"
      },
      {
        "itemid": "2612715",
        "clock": "1589871600",
        "num": "1",
        "value_min": "15.0927",
        "value_avg": "15.0927",
        "value_max": "15.0927"
      },
      {
        "itemid": "2612715",
        "clock": "1589878800",
        "num": "1",
        "value_min": "15.1206",
        "value_avg": "15.1206",
        "value_max": "15.1206"
      },
      {
        "itemid": "2612715",
        "clock": "1589886000",
        "num": "1",
        "value_min": "15.1545",
        "value_avg": "15.1545",
        "value_max": "15.1545"
      },
      {
        "itemid": "2612715",
        "clock": "1589893200",
        "num": "1",
        "value_min": "15.1745",
        "value_avg": "15.1745",
        "value_max": "15.1745"
      },
      {
        "itemid": "2612715",
        "clock": "1589900400",
        "num": "1",
        "value_min": "15.1975",
        "value_avg": "15.1975",
        "value_max": "15.1975"
      },
      {
        "itemid": "2612715",
        "clock": "1589907600",
        "num": "1",
        "value_min": "15.2116",
        "value_avg": "15.2116",
        "value_max": "15.2116"
      },
      {
        "itemid": "2612715",
        "clock": "1589914800",
        "num": "1",
        "value_min": "15.2291",
        "value_avg": "15.2291",
        "value_max": "15.2291"
      },
      {
        "itemid": "2612715",
        "clock": "1589922000",
        "num": "1",
        "value_min": "15.2430",
        "value_avg": "15.2430",
        "value_max": "15.2430"
      },
      {
        "itemid": "2612715",
        "clock": "1589929200",
        "num": "1",
        "value_min": "15.2592",
        "value_avg": "15.2592",
        "value_max": "15.2592"
      },
      {
        "itemid": "2612715",
        "clock": "1589936400",
        "num": "1",
        "value_min": "15.2707",
        "value_avg": "15.2707",
        "value_max": "15.2707"
      },
      {
        "itemid": "2612715",
        "clock": "1589943600",
        "num": "1",
        "value_min": "15.0203",
        "value_avg": "15.0203",
        "value_max": "15.0203"
      },
      {
        "itemid": "2612715",
        "clock": "1589950800",
        "num": "1",
        "value_min": "15.0597",
        "value_avg": "15.0597",
        "value_max": "15.0597"
      },
      {
        "itemid": "2612715",
        "clock": "1589958000",
        "num": "1",
        "value_min": "15.0901",
        "value_avg": "15.0901",
        "value_max": "15.0901"
      },
      {
        "itemid": "2612715",
        "clock": "1589965200",
        "num": "1",
        "value_min": "15.1181",
        "value_avg": "15.1181",
        "value_max": "15.1181"
      },
      {
        "itemid": "2612715",
        "clock": "1589972400",
        "num": "1",
        "value_min": "15.1444",
        "value_avg": "15.1444",
        "value_max": "15.1444"
      },
      {
        "itemid": "2612715",
        "clock": "1589979600",
        "num": "1",
        "value_min": "15.1717",
        "value_avg": "15.1717",
        "value_max": "15.1717"
      },
      {
        "itemid": "2612715",
        "clock": "1589986800",
        "num": "1",
        "value_min": "15.1933",
        "value_avg": "15.1933",
        "value_max": "15.1933"
      },
      {
        "itemid": "2612715",
        "clock": "1589994000",
        "num": "1",
        "value_min": "15.2117",
        "value_avg": "15.2117",
        "value_max": "15.2117"
      },
      {
        "itemid": "2612715",
        "clock": "1590001200",
        "num": "1",
        "value_min": "15.2259",
        "value_avg": "15.2259",
        "value_max": "15.2259"
      },
      {
        "itemid": "2612715",
        "clock": "1590008400",
        "num": "1",
        "value_min": "15.2436",
        "value_avg": "15.2436",
        "value_max": "15.2436"
      },
      {
        "itemid": "2612715",
        "clock": "1590015600",
        "num": "1",
        "value_min": "15.2578",
        "value_avg": "15.2578",
        "value_max": "15.2578"
      },
      {
        "itemid": "2612715",
        "clock": "1590022800",
        "num": "1",
        "value_min": "15.2776",
        "value_avg": "15.2776",
        "value_max": "15.2776"
      },
      {
        "itemid": "2612715",
        "clock": "1590030000",
        "num": "1",
        "value_min": "15.0253",
        "value_avg": "15.0253",
        "value_max": "15.0253"
      },
      {
        "itemid": "2612715",
        "clock": "1590037200",
        "num": "1",
        "value_min": "15.0607",
        "value_avg": "15.0607",
        "value_max": "15.0607"
      },
      {
        "itemid": "2612715",
        "clock": "1590048000",
        "num": "1",
        "value_min": "14.9567",
        "value_avg": "14.9567",
        "value_max": "14.9567"
      },
      {
        "itemid": "2612715",
        "clock": "1590058800",
        "num": "1",
        "value_min": "14.9791",
        "value_avg": "14.9791",
        "value_max": "14.9791"
      },
      {
        "itemid": "2612715",
        "clock": "1590066000",
        "num": "1",
        "value_min": "15.2334",
        "value_avg": "15.2334",
        "value_max": "15.2334"
      },
      {
        "itemid": "2612715",
        "clock": "1590073200",
        "num": "1",
        "value_min": "15.2719",
        "value_avg": "15.2719",
        "value_max": "15.2719"
      },
      {
        "itemid": "2612715",
        "clock": "1590080400",
        "num": "1",
        "value_min": "15.3025",
        "value_avg": "15.3025",
        "value_max": "15.3025"
      },
      {
        "itemid": "2612715",
        "clock": "1590087600",
        "num": "1",
        "value_min": "15.3445",
        "value_avg": "15.3445",
        "value_max": "15.3445"
      },
      {
        "itemid": "2612715",
        "clock": "1590102000",
        "num": "1",
        "value_min": "15.3931",
        "value_avg": "15.3931",
        "value_max": "15.3931"
      },
      {
        "itemid": "2612715",
        "clock": "1590109200",
        "num": "1",
        "value_min": "16.0955",
        "value_avg": "16.0955",
        "value_max": "16.0955"
      },
      {
        "itemid": "2612715",
        "clock": "1590116400",
        "num": "1",
        "value_min": "15.0514",
        "value_avg": "15.0514",
        "value_max": "15.0514"
      },
      {
        "itemid": "2612715",
        "clock": "1590123600",
        "num": "1",
        "value_min": "15.1148",
        "value_avg": "15.1148",
        "value_max": "15.1148"
      },
      {
        "itemid": "2612715",
        "clock": "1590130800",
        "num": "1",
        "value_min": "15.1663",
        "value_avg": "15.1663",
        "value_max": "15.1663"
      }
    ],
    "id": 1
  }
}

**Comment by alexanderzobnin** [comment]
This error caused by missing trigger with `objectid` obtained from the `problem.get`. That's strange, I'm trying to imagine a situation where it can happen. Plugin fetches problems, then get trigger ids from the response, and get triggers with that ids. And if trigger is not exist, this error happens. But what's a reason?

**Comment by alexanderzobnin** [comment]
@duuz that's a wrong response (for `trend.get`).

**Comment by forum77alive** [comment]
+1

**Comment by alexanderzobnin** [comment]
Ok, I've managed to reproduce this. Bug happens when you have a problem linked to the not monitored trigger (with disabled item, for instance).

**Comment by alexanderzobnin** [comment]
Fixed in 13b0a2db787d763c53ace8876d7aca7ee9bae5bc

**Comment by JSylvia007** [comment]
I can confirm that the update fixed my issue.

Grafana v7.0.0 (aee1438ff2)
Zabbix Plugin Version 3.12.1
Zabbix Server 4.4.8
Ubunti 18.04.4

**Comment by forum77alive** [comment]
My issue (cannot read property 'description' of undefined) fixed too, but now i get "Cannot read property 'length' of undefined" on one of the zabbix-servers

**Comment by sirovstrukelj** [comment]
I've updated from 3.12.0 and the issue persisted until I cleared all the cookies related in my browser to the domain where Grafana was running.
